@api=http://localhost:8080

###
GET {{api}}

###
# @name createUser
POST {{api}}/user
Content-Type: application/json

{
    "name": "lucas",
    "email": "12345@gmail.com",
    "password": "123"
}

###
# @name authenticateUser
POST {{api}}/sessions
Content-Type: application/json

{
    "email": "12345@gmail.com",
    "password": "123"
}